import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface Props {
  header?: boolean;
}

export default function RootLayout({
  children,
  props,
}: Readonly<{
  children?: React.ReactNode,
  props?: Props,
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {props?.header && <header>
          <h1>Intelligent Flashcards</h1></header>}
        {children}
      </body>
    </html>
  );
}
