"use client";

import React, { useState, useEffect, useRef } from "react";

interface AIChatbotProps {
  isOpen: boolean;
  onClose: () => void;
  onAddFlashcard: (word: string, definition: string) => void;
}

interface Message {
  sender: "user" | "ai";
  text: string;
}

export default function AIChatbot({
  isOpen,
  onClose,
  onAddFlashcard,
}: AIChatbotProps) {
  const [messages, setMessages] = useState<Message[]>([]);
  const [input, setInput] = useState("");
  const messagesEndRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    if (isOpen) {
      setMessages([
        {
          sender: "ai",
          text: "Hello! I can help you create flashcards. What topic or specific flashcard would you like to create?",
        },
      ]);
    } else {
      setMessages([]); // Clear messages when closed
    }
  }, [isOpen]);

  useEffect(() => {
    messagesEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages]);

  const handleSendMessage = () => {
    if (input.trim() === "") return;

    const userMessage: Message = { sender: "user", text: input };
    setMessages((prevMessages) => [...prevMessages, userMessage]);
    setInput("");

    // Simulate AI response
    setTimeout(() => {
      const aiResponseText = `I can create a flashcard for "${input}". Would you like to add this to your set? (e.g., "Yes, add it" or "No")`;
      const aiMessage: Message = { sender: "ai", text: aiResponseText };
      setMessages((prevMessages) => [...prevMessages, aiMessage]);
    }, 1000);
  };

  const handleKeyPress = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      handleSendMessage();
    }
  };

  const handleAddResponse = (response: string) => {
    if (response.toLowerCase().includes("yes, add it")) {
      // This is a mock for now. In a real scenario, AI would parse the user's input
      // and provide the word and definition. For this task, we'll just use the last user input.
      const lastUserMessage = messages.findLast((msg) => msg.sender === "user");
      if (lastUserMessage) {
        // Simple parsing for demonstration.
        // In a real AI, you'd get structured data.
        const wordMatch = lastUserMessage.text; // Assuming the user's last input is the word
        const definitionMatch = "Definition generated by AI (mock)"; // Placeholder

        if (wordMatch) {
          onAddFlashcard(wordMatch, definitionMatch);
          setMessages((prevMessages) => [
            ...prevMessages,
            { sender: "ai", text: `"${wordMatch}" added to your set!` },
          ]);
        }
      }
    }
  };

  if (!isOpen) return null;

  return (
    <div className="fixed inset-0 bg-gray-600 bg-opacity-50 flex items-center justify-center z-50">
      <div className="bg-white rounded-lg shadow-xl w-full max-w-md flex flex-col" style={{ height: "80vh" }}>
        <div className="flex justify-between items-center p-4 border-b">
          <h2 className="text-lg font-semibold">AI Flashcard Assistant</h2>
          <button onClick={onClose} className="text-gray-500 hover:text-gray-700">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-6 w-6"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M6 18L18 6M6 6l12 12"
              />
            </svg>
          </button>
        </div>

        <div className="flex-1 p-4 overflow-y-auto">
          {messages.map((msg, index) => (
            <div
              key={index}
              className={`mb-2 ${
                msg.sender === "user" ? "text-right" : "text-left"
              }`}
            >
              <span
                className={`inline-block p-2 rounded-lg ${
                  msg.sender === "user"
                    ? "bg-blue-500 text-white"
                    : "bg-gray-200 text-gray-800"
                }`}
              >
                {msg.text}
              </span>
            </div>
          ))}
          <div ref={messagesEndRef} />
        </div>

        <div className="p-4 border-t flex">
          <input
            type="text"
            className="flex-1 rounded-md border-gray-300 shadow-sm focus:border-indigo-300 focus:ring focus:ring-indigo-200 focus:ring-opacity-50 mr-2"
            placeholder="Type your message..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            onKeyPress={handleKeyPress}
          />
          <button
            onClick={handleSendMessage}
            className="px-4 py-2 bg-blue-500 text-white rounded-md hover:bg-blue-600 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:ring-opacity-50"
          >
            Send
          </button>
        </div>
      </div>
    </div>
  );
}